gstbilling/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gstbillingapp.urls')),
    path('', include('social_django.urls', namespace='social'))
]

gstbillingapp/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime
# Create your models here.

# ========================== Saas Data models ==================================

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    business_title = models.CharField(max_length=100, blank=True, null=True)
    business_address = models.TextField(max_length=400, blank=True, null=True)
    business_email = models.EmailField(blank=True, null=True)
    business_phone = models.CharField(max_length=20, blank=True, null=True)
    business_gst = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return self.user.username


class Plan(models.Model):
    plan_name = models.TextField(max_length=20, blank=True, null=True)
    plan_value = models.IntegerField(blank=True, null=True)
    monthly_invoice_limit = models.IntegerField(blank=True, null=True)


class BillingProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    plan = models.ForeignKey(Plan, blank=True, null=True, on_delete=models.SET_NULL)
    plan_start_date = models.DateField(blank=True, null=True)
    plan_end_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.user.username

# ======================= Invoice Data models =================================

class Customer(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    customer_name = models.CharField(max_length=200)
    customer_address = models.TextField(max_length=600, blank=True, null=True)
    customer_phone = models.CharField(max_length=14, blank=True, null=True)
    customer_gst = models.CharField(max_length=15, blank=True, null=True)
    def __str__(self):
        return self.customer_name


class Invoice(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    invoice_number = models.IntegerField()
    invoice_date = models.DateField()
    invoice_customer = models.ForeignKey(
        'Customer',
        on_delete=models.SET_NULL,
        null=True
    )
    invoice_json = models.TextField()
    inventory_reflected = models.BooleanField(default=True)
    books_reflected = models.BooleanField(default=True)
    def __str__(self):
        return str(self.invoice_number) + " | " + str(self.invoice_date)


class Product(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    product_name = models.CharField(max_length=200)
    product_hsn = models.CharField(max_length=50, null=True, blank=True)
    product_unit = models.CharField(max_length=50)
    product_gst_percentage = models.FloatField()
    product_rate_with_gst = models.FloatField()
    def __str__(self):
        return str(self.product_name)

# ========================= Inventory Data models ====================================
class InventoryLog(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.SET_NULL)
    date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    last_modified = models.DateTimeField(auto_now=True)
    change = models.IntegerField(default=0)
    CHANGE_TYPES = [
        (0, 'Other'),
        (1, 'Purchase'),
        (2, 'Production'),
        (4, 'Sales'),
    ]
    change_type = models.IntegerField(choices=CHANGE_TYPES, default=0)

    associated_invoice = models.ForeignKey(Invoice, blank=True, null=True, default=None, on_delete=models.SET_NULL)
    description = models.TextField(max_length=600, blank=True, null=True)

    def __str__(self):
        return self.product.product_name + " | " + str(self.change) + " | " + self.description + " | " + str(self.date)

class Inventory(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.SET_NULL)
    current_stock = models.IntegerField(default=0)
    alert_level = models.IntegerField(default=0)
    last_log = models.ForeignKey(InventoryLog, null=True, blank=True, default=None, on_delete=models.SET_NULL)

    def __str__(self):
        return self.product.product_name

# ========================= Books Data models ======================================

class Book(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL)
    current_balance = models.FloatField(default=0)
    last_log = models.ForeignKey('BookLog', null=True, blank=True, default=None, on_delete=models.SET_NULL)

    def __str__(self):
        return self.customer.customer_name


class BookLog(models.Model):
    parent_book = models.ForeignKey(Book, null=True, blank=True, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    last_modified = models.DateTimeField(auto_now=True)
    CHANGE_TYPES = [
        (0, 'Paid'),
        (1, 'Purchased Items'),
        (2, 'Sold Items'),
        (4, 'Other'),
    ]
    change_type = models.IntegerField(choices=CHANGE_TYPES, default=0)
    change = models.FloatField(default=0.0)

    associated_invoice = models.ForeignKey(Invoice, blank=True, null=True, default=None, on_delete=models.SET_NULL)
    description = models.TextField(max_length=600, blank=True, null=True)

    def __str__(self):
        return self.parent_book.customer.customer_name + " | " + str(self.change) + " | " + self.description + " | " + str(self.date)


gstbillingapp/forms.py
from django.forms import ModelForm
from .models import Customer
from .models import Product
from .models import UserProfile
from .models import InventoryLog
from .models import BookLog


class CustomerForm(ModelForm):
     class Meta:
         model = Customer
         fields = ['customer_name', 'customer_address', 'customer_phone', 'customer_gst']


class ProductForm(ModelForm):
     class Meta:
         model = Product
         fields = ['product_name', 'product_hsn', 'product_unit', 'product_gst_percentage', 'product_rate_with_gst']


class UserProfileForm(ModelForm):
    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(UserProfileForm, self).__init__(*args, **kwargs)
        # there's a `fields` property now
        self.fields['business_title'].required = True

    class Meta:
        model = UserProfile
        fields = ['business_title', 'business_address', 'business_email', 'business_phone', 'business_gst']


class InventoryLogForm(ModelForm):
    class Meta:
        model = InventoryLog
        fields = ['date', 'change', 'change_type', 'description']


class BookLogForm(ModelForm):
    class Meta:
        model = BookLog
        fields = ['date', 'change', 'change_type', 'description']

gstbillingapp/templates/gstbillingapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>
		{% block title %}
		GST Billing
		{% endblock %}
	</title>

	{% block metatags %}
	{% endblock %}



	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static "gstbillingapp/bootstrap-4.4.1-dist/css/bootstrap-cosmo.min.css" %}">
	<link rel="stylesheet" href="{% static "gstbillingapp/main.css" %}">

	<!-- DataTables CSS  -->
	<link rel="stylesheet" href="{% static "gstbillingapp/DataTables/jquery.dataTables.min.css" %}">
	<link rel="stylesheet" href="{% static "gstbillingapp/DataTables/dataTables.bootstrap4.min.css" %}">

	{% block includecss %}
	{% endblock %}

</head>

<body>

	<div class="container">
		<!-- Content here -->

		{% include "gstbillingapp/navbar.html" %}

		{% if error_message %}
		<div class="alert alert-danger" role="alert">
			{{error_message}}
		</div>
		{% endif %}

		{% if success_message %}
		<div class="alert alert-success" role="alert">
			{{success_message}}
		</div>
		{% endif %}

		{% block content %}
		CONTENT BLOCK
		{% endblock %}

	</div>




	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	
	<!-- 	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script> -->
	<script src="{% static "gstbillingapp/js/jquery-3.4.1.min.js" %}"></script>
	<script src="{% static "gstbillingapp/js/popper.min.js" %}"></script>

	<script src="{% static "gstbillingapp/bootstrap-4.4.1-dist/js/bootstrap.min.js" %}"></script>

	<!-- DataTables  -->
	<script src="{% static "gstbillingapp/DataTables/jquery.dataTables.min.js" %}"></script>


	{% block includejs %}
	{% endblock %}



<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-159304253-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-159304253-1');
</script>



</body>


</html>

gstbillingapp/templates/gstbillingapp/book_logs_add.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}
<h2>Update Book</h2>

<hr>
<div class="row">
	<div class="col">
		<h3>Customer: {{book.customer.customer_name}}</h3>
		<h3>Current Balance: {{book.current_balance}}</h3>
	</div>
</div>


<form method="POST">
	{% csrf_token %}
	<table class="table">
		<tbody class="two-col-form">
			<tr>
				<th scope="row" class="text-right">Date & Time:</th>
				<td class="form-input-td customer_search_area">{{form.date}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Change in balance:</th>
				<td class="form-input-td">{{form.change}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Change Type:</th>
				<td class="form-input-td">{{form.change_type}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Associated Invoice Number:</th>
				<td class="form-input-td"><input type="text" name="invoice_no"></ins></td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Desription:</th>
				<td class="form-input-td">{{form.description}}</td>
			</tr>
		</tbody>
	</table>

	<input type="submit" class="btn btn-primary float-right" value="Submit">
</form>

{% endblock %}

gstbillingapp/templates/gstbillingapp/books.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}
<div class="row">
	<div class="col">
		<h2>Book</h2>
	</div>
</div>

<table class="table table-hover font-weight-bold" id="book-table">
	<thead>
		<tr>
			<th>Customer</th>
			<th>Current Balance</th>
			<th>Last Transaction</th>
		</tr>
	</thead>
	<tbody class="two-col-form">
		{% for book in book_list %}
		<tr onclick="window.location='{% url 'book_logs' book.id %}';">
			<td><a href="{% url 'book_logs' book.id %}">{{book.customer.customer_name}}</a></td>
			<td>{{book.current_balance}}</td>
			<td>{{book.last_log}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>


{% endblock %}


{% block includejs %}
<script type="text/javascript">

$(document).ready( function () {
	$('#book-table').DataTable({
		"order": [],
		"columnDefs": [ {
			"targets": 3,
			"sortable": false,
			"searchable": false
		} ],
		"paging": true
	});
});

</script>
{% endblock %}

gstbillingapp/templates/gstbillingapp/inventory.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}
<div class="row">
	<div class="col">
		<h2>Inventory</h2>
	</div>
</div>

<table class="table table-hover font-weight-bold" id="inventory-table">
	<thead>
		<tr>
			<th>Product</th>
			<th>Current Stock</th>
			<th>Last Transaction</th>
		</tr>
	</thead>
	<tbody class="two-col-form">
		{% for inventory in inventory_list %}
		<tr onclick="window.location='{% url 'inventory_logs' inventory.id %}';">
			<td><a href="{% url 'inventory_logs' inventory.id %}">{{inventory.product.product_name}}</a></td>
			<td>{{inventory.current_stock}}</td>
			<td>{{inventory.last_log}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>


{% endblock %}


{% block includejs %}
<script type="text/javascript">

$(document).ready( function () {
	$('#inventory-table').DataTable({
		"order": [],
		"columnDefs": [ {
			"targets": 3,
			"sortable": false,
			"searchable": false
		} ],
		"paging": true
	});
});

</script>
{% endblock %}

gstbillingapp/templates/gstbillingapp/inventory_logs.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}
<h2>Inventory Details</h2>
<hr>

<div class="row">
	<div class="col">
		<h3>Product: {{inventory.product}}</h3>
		<h3>Current Stock: {{inventory.current_stock}}</h3>
	</div>
	<div class="col">
		<a href="{% url 'inventory_logs_add' inventory.id %}" id="add_customer_btn"><button type="button" class="btn btn-primary">Add Update</button></a>
	</div>
</div>

<hr>

<table class="table table-hover font-weight-bold" id="inventory-logs-table">
	<thead>
		<tr>
			<th>Date</th>
			<th>Type</th>
			<th>Description</th>
			<th>Change</th>
		</tr>
	</thead>
	<tbody class="two-col-form">
		{% for item in inventory_logs %}
		<tr class="{% if item.change < 0 %}table-danger{% else %}table-success{%endif%}">
			<td>{{item.date}}</td>
			<td>{{item.get_change_type_display}} {% if item.associated_invoice %}<a href="{% url 'invoice_viewer' item.associated_invoice.id %}">[INVOICE]</a>{% endif %}</td>
			<td>{{item.description}}</td>
			<td class="text-right">{{item.change}} &emsp; {{inventory.product.product_unit}}</td>
		{% endfor %}
	</tbody>
</table>



{% endblock %}


{% block includejs %}
<script type="text/javascript">
$(document).ready( function () {
	$('#inventory-logs-table').DataTable({
		"order": [],
		"paging": true,
	});
});

</script>
{% endblock %}

gstbillingapp/templates/gstbillingapp/invoice_printer.html
{% extends "gstbillingapp/print_base.html" %}


{% block content %}

	<div class="card">
		<div class="card-header">
			<div class="row">
			<div class="col-sm-6 col-6"><strong>Invoice Date: {{invoice.invoice_date}}</strong></div> 
			<div class="col-sm-6 text-right col-6"><strong>Invoice No:{{invoice.invoice_number}}</strong></div>
			</div>
		</div>

		<div class="card-body">
			<div class="row">


				<div class="col-sm-6 col-md-6 col-lg-6 col-6">
					<div>
						<strong>{{user_profile.business_title}}</strong>
					</div>
						<div id="invoice_profile_data">{{user_profile.business_address}}</div>
					{% if user_profile.business_email %}
						<div>EMAIL: {{user_profile.business_email}}</div>
					{% endif %}
					{% if user_profile.business_phone %}
						<div>Phone: {{user_profile.business_phone}}</div>
					{% endif %}
					{% if user_profile.business_gst %}
						<div>GST No: {{user_profile.business_gst}}</div>
					{% endif %}
				</div>



				<div class="col-sm-6 col-md-6 col-lg-6 col-6">
					<h6 class="mb-3">Billed To:</h6>
					<div>
						<strong>{{ invoice_data.customer_name }}</strong>
					</div>
					<div>{{ invoice_data.customer_address }}</div>
					<div>Phone: {{ invoice_data.customer_phone }}</div>
					<div>GST No: {{ invoice_data.customer_gst }}</div>
					{% if invoice_data.vehicle_number %}
					<div><strong>Vehicle No:</strong> {{ invoice_data.vehicle_number }}</div>
					{% endif %}
				</div>



			</div>

			<div class="table-responsive-sm">
				<table class="table table-striped table-invoice">
					<thead>
						<tr>
							<th class="text-center">#</th>
							<th class="text-left">Item</th>
							<th class="text-center">HSN / SAC</th>
							<th class="text-center">Unit</th>
							<th class="text-right">Qty</th>
							<th class="text-right">Rate ({{ currency }})</th>
							<th class="text-right">Taxable Amount ({{ currency }})</th>
							<th class="text-right">GST (%)</th>
							{% if invoice_data.igstcheck %}
								<th class="text-right">IGST ({{ currency }})</th>
							{% else %}
								<th class="text-right">CGST ({{ currency }})</th>
								<th class="text-right">SGST ({{ currency }})</th>
							{% endif %}
							<th class="text-right">Total Amount ({{ currency }})</th>

						</tr>
					</thead>
					<tbody>
						{% for item in invoice_data.items %}
						<tr>
							<td class="text-center">{{ forloop.counter }}</td>
							<td class="text-left strong">{{ item.invoice_product }}</td>
							<td class="text-center">{{ item.invoice_hsn }}</td>
							<td class="text-center">{{ item.invoice_unit }}</td>
							<td class="text-right">{{ item.invoice_qty }}</td>
							<td class="text-right">{{ item.invoice_rate_without_gst|floatformat:2 }}</td>
							<td class="text-right">{{ item.invoice_amt_without_gst|floatformat:2 }}</td>
							<td class="text-right">{{ item.invoice_gst_percentage }}</td>
							{% if invoice_data.igstcheck %}
								<td class="text-right">{{ item.invoice_amt_igst|floatformat:2 }}</td>
							{% else %}
								<td class="text-right">{{ item.invoice_amt_cgst|floatformat:2 }}</td>
								<td class="text-right">{{ item.invoice_amt_sgst|floatformat:2 }}</td>
							{% endif %}
							<td class="text-right">{{ item.invoice_amt_with_gst|floatformat:2 }}</td>
						</tr>
						{% endfor %}

						<tr id="table-invoice-total-row">
							{% if invoice_data.igstcheck %}
								<td class="text-right" colspan="6">Total: </td>
								<td class="text-right">{{ currency }} {{ invoice_data.invoice_total_amt_without_gst|floatformat:2 }}</td>
								<td class="text-right"></td>
								<td class="text-right">{{ currency }} {{invoice_data.invoice_total_amt_igst|floatformat:2 }}</td>
							{% else %}
								<td class="text-right" colspan="6">Total: </td>
								<td class="text-right">{{ currency }} {{ invoice_data.invoice_total_amt_without_gst|floatformat:2 }}</td>
								<td class="text-right"></td>
								<td class="text-right">{{ currency }} {{invoice_data.invoice_total_amt_cgst|floatformat:2 }}</td>
								<td class="text-right">{{ currency }} {{invoice_data.invoice_total_amt_sgst|floatformat:2 }}</td>
							{% endif %}
							<td class="text-right"><strong>{{ currency }} {{ invoice_data.invoice_total_amt_with_gst|floatformat:2 }}</strong></td>
						</tr>

					</tbody>
				</table>
			</div>

			<div class="row">


				<div class="col-sm-6 col-lg-6 col-md-6">
					
				</div>

				<div class="col-sm-6 col-lg-6 col-md-6">
					<table class="table text-right" id="invoice-grand-total-table">
						<tr>
							<td>Total Taxable Amount: </td>
							<td>{{ currency }} {{ invoice_data.invoice_total_amt_without_gst|floatformat:2 }}</td>
						</tr>
						{% if invoice_data.igstcheck %}
							<tr>
								<td>IGST: </td>
								<td>{{ currency }} {{ invoice_data.invoice_total_amt_igst|floatformat:2 }}</td>
							</tr>
						{% else %}
							<tr>
								<td>CGST: </td>
								<td>{{ currency }} {{ invoice_data.invoice_total_amt_cgst|floatformat:2 }}</td>
							</tr>
							<tr>
								<td>SGST: </td>
								<td>{{ currency }} {{ invoice_data.invoice_total_amt_sgst|floatformat:2 }}</td>
							</tr>
						{% endif %}
						<tr>
							<td>Invoice Total: </td>
							<td>{{ currency }} {{invoice_data.invoice_total_amt_with_gst|floatformat:2 }}</td>
						</tr>
						<tr> 
							<td colspan="2" class="text-middle">
								Invoice Total In Words: {{ total_in_words }} only.
							</td>
						</tr>
						<tr id="invoice-signature-row">
							<td colspan="2"></td>
						</tr>
						<tr id="invoice-signature-text-row">
							<td colspan="2">Authorized Signatory<br> E, & O.E.	</td>
						</tr>
					</table>


				</div>



			</div>


		</div>
	</div>

	<button onclick="window.print();" class="btn btn-primary d-print-none">Print Invoice</button>


{% endblock %}

gstbillingapp/templates/gstbillingapp/login.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}
<div class="row">
<div class="col-sm">
</div>
<div class="col-sm">
	<div class="card" id="login-card">
		<h5 class="card-header">Login</h5>
		<div class="card-body">
			<h5 class="card-title">Login and start billing now!</h5>
			<!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
			<!--a href="{% url "social:begin" "google-oauth2" %}" class="btn btn-primary">Login with Google</a-->
		</div>
		<div>OR</div>
		<form method="POST">
			{% csrf_token %}
			<table class="table">
				<tbody class="two-col-form">
					<tr>
						<th scope="row" class="text-right">Username:</th>
						<td class="form-input-td">{{auth_form.username}}</td>
					</tr>`
					<tr>
						<th scope="row" class="text-right">Password:</th>
						<td class="form-input-td">{{auth_form.password}}</td>
					</tr>
				</tbody>
			</table>
		
			<input type="submit" class="btn btn-primary float-right" value="Submit">
		</form>

		
	</div>
		<a href="{% url 'signup_view' %}"><input class="btn btn-danger float-right" value="Sign Up"></a>
	</div>
<div class="col-sm">
</div>
</div>
{% endblock %}

gstbillingapp/templates/gstbillingapp/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="{% url 'landing_page' %}">Python Django GST Billing</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			{% if user.is_authenticated %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'invoice_create' %}">New Invoice <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'invoices' %}">Invoices</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'inventory' %}">Inventory</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'books' %}">Books</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'customers' %}">Customers</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'products' %}">Products</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user_profile' %}">Profile</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'logout' %}?next=/">Logout</a>
			</li>
			{% endif %}
		</ul>
	</div>
</nav>

gstbillingapp/templates/gstbillingapp/print_base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>
		{% block title %}
		GST Billing
		{% endblock %}
	</title>



	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static "gstbillingapp/bootstrap-4.4.1-dist/css/bootstrap-cosmo.min.css" %}">
	<link rel="stylesheet" href="{% static "gstbillingapp/main.css" %}">

	<!-- DataTables CSS  -->
	<link rel="stylesheet" href="{% static "gstbillingapp/DataTables/jquery.dataTables.min.css" %}">
	<link rel="stylesheet" href="{% static "gstbillingapp/DataTables/dataTables.bootstrap4.min.css" %}">

	{% block includecss %}
	{% endblock %}

</head>

<body>

	{% include "gstbillingapp/navbar.html" %}





		{% block content %}
		CONTENT BLOCK
		{% endblock %}





	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="{% static "gstbillingapp/js/jquery-3.4.1.min.js" %}"></script>
	<script src="{% static "gstbillingapp/js/popper.min.js" %}"></script>

	<script src="{% static "gstbillingapp/bootstrap-4.4.1-dist/js/bootstrap.min.js" %}"></script>

	<!-- DataTables  -->
	<script src="{% static "gstbillingapp/DataTables/jquery.dataTables.min.js" %}"></script>

	{% block includejs %}
	{% endblock %}

</body>


</html>

gstbillingapp/templates/gstbillingapp/product_edit.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}

<h2>Edit Product</h2>
<form method="POST">
	{% csrf_token %}
	<table class="table">
		<tbody class="two-col-form">
			<tr>
				<th scope="row" class="text-right">Product Name:</th>
				<td class="form-input-td">{{product_form.product_name}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">HSN:</th>
				<td class="form-input-td">{{product_form.product_hsn}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Product Unit:</th>
				<td class="form-input-td">{{product_form.product_unit}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">GST %:</th>
				<td class="form-input-td">{{product_form.product_gst_percentage}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Rate with GST:</th>
				<td class="form-input-td">{{product_form.product_rate_with_gst}}</td>
			</tr>
		</tbody>
	</table>

	<input type="submit" class="btn btn-primary float-right" value="Submit">
</form>
{% endblock %}

gstbillingapp/templates/gstbillingapp/user_profile.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}
	<div class="row">
		<div class="col">
			<h2>Profile</h2>
		</div>
		<div class="col">
			<a href="{% url 'user_profile_edit' %}" id="user_profile_edit_btn"><button type="button" class="btn btn-primary">Edit</button></a>
		</div>
	</div>
	<table class="table">
		<tbody class="two-col-form">
			<tr>
				<th scope="row" class="text-right">Business Name:</th>
				<td class="form-input-td customer_search_area">{{user_profile.business_title}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Address:</th>
				<td class="form-input-td">{{user_profile.business_address}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Email:</th>
				<td class="form-input-td">{{user_profile.business_email}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">Phone:</th>
				<td class="form-input-td">{{user_profile.business_phone}}</td>
			</tr>
			<tr>
				<th scope="row" class="text-right">GST:</th>
				<td class="form-input-td">{{user_profile.business_gst}}</td>
			</tr>
		</tbody>
	</table>

{% endblock %}